# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Konrad Wiecko
title: Machine Learning Engineer / Data Scientist
email: konrad.wiecko@gmail.com
website: https://kwiecko.github.io/resume/
location: Warsaw, Poland

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  KWiecko
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: konrad-więcko-88a81010b
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: upwork.com
  icon: fas fa-globe
  url: https://www.upwork.com/freelancers/~011ad5169826c1c47f?viewMode=1
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_li.jpeg
about_content: | # this will include new lines to allow paragraphs
  Machine learning engineer / Data scientist. 6+ years of professional ML / DS experience working for brands like Samsung, mBank and PKN Orlen. 
  Currently working as a co-developer of [Improve AI](https://improve.ai/) - a fast and lightweight RL-based recommendation engine.
  Passionate about combining Computer Vision with UAV / drone tech. 

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience and Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Improve AI
        link: https://improve.ai
        link_text: https://improve.ai
        sub_title: Machine Learning Engineer / Data Scientist
        caption: September 2020 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          <mark>reinforcement learning</mark>  <mark>multi-armed contextual bandits</mark>  <mark>ML</mark> <mark>docker</mark> 
          
          
          Co-developing fast, AWS based recommendation platform for JSON encodable data. Working directly with CTO / founder / solution architect (managed 1 additional developer along the way for a while).
          Contributing significantly at the every stage of platform's development:
          - [python SDK](https://github.com/improve-ai/python-ranker) - development and testing
          - [AWS platform](https://github.com/improve-ai/tracker) - development, optimization, testing and deployment of various components (data ingestion, orchestration, dockerization)
          - RL / ML models training and deployment - development of distributed training pipeline, debugging, model validation, testing and deployment (e.g. cross-platform predictions consistency)
            
             
          <img src="images/python.jpg" width="25" height="25" /> <mark>Python3.8+</mark>:  <mark>XGBoost</mark>  <mark>numpy</mark>  <mark>pandas</mark>  <mark>dask</mark>  <mark>dask-ml</mark>  <mark>cython</mark>  <mark>fastparquet</mark>  <mark>matplotlib</mark>  <mark>coba</mark>  <mark>boto3</mark>  <mark>pytest</mark>  <mark>tox</mark>
          
          <img src="images/aws.png" width="25" height="25" /> <mark>AWS</mark>:  <mark>SageMaker</mark>  <mark>Lambda</mark>  <mark>S3</mark>  <mark>ECR</mark>  <mark>StepFunctions</mark>  <mark>Firehose</mark>  <mark>serverless</mark>

  - title:  #  Experience and Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Additional projects
#        link: mbank
#        link_text: https://www.mbank.pl/
        sub_title: Deep Learning / Computer Vision
        caption: March 2021 - until now
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          <mark>deep learning</mark>  <mark>computer vision</mark>  <mark>u-net</mark>  <mark>fpn</mark>  <mark>time series analysis</mark>  <mark>web scraping</mark> <mark>docker</mark> <mark>docker-compose</mark>
          
          - image segmentation for agriculture [](https://www.agriculture-vision.com/); integration of the trained model with DJI drone via video streaming
          - Steam games sales prediction with LSTM - from automated data scraping and storing in PostgreSQL DB to LSTM-based model training; github will be available soon
          - finalist of the [CUValleyHack 2021](https://2021.cuvalley.com/) - muchDS team
             
          <img src="images/python.jpg" width="25" height="25" /> <mark>Python3.7.9</mark>:  <mark>tensorflow</mark>  <mark>XGBoost</mark>  <mark>numpy</mark>  <mark>pandas</mark>  <mark>matplotlib</mark>  <mark>Beautiful Soup</mark>  <mark>pytest</mark>  <mark>tox</mark>
          
          <img src="images/db_logo.jpg" width="25" height="25" /> <mark>DB stack</mark>:  <mark>PostgreSQL</mark>


  - title:  #  Experience and Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: mBank
        link: https://www.mbank.pl/
        link_text: https://www.mbank.pl/
        sub_title: Machine Learning Engineer / Data Scientist
        caption: July 2019 - August 2021
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          <mark>ML</mark>  <mark>churn prediction</mark>  <mark>time series analysis</mark>  <mark>process mining</mark>  <mark>process optimization</mark>
          
          - corporate client churn prediction - fully responsible for development of a robust time series <mark>XGBoost</mark> classifier (~30% precision / ~50% recall); Extensive sklearn's API usage to combine an entire process into a single pipelines; Actively participated in production deployment and monitoring
          - process optimization - developed and deployed multiple data transformation and ingestion pipelines (bank's DW &rarr; process mining tool LanaLabs via REST API); Automation of bank's job scheduler config creation
          - responsible for developing and maintaining an ad-hoc, internally hosted CoVid-19 R-Shiny report for bank's management 
          
            
             
          <img src="images/python.jpg" width="25" height="25" /> <mark>Python3.7.9</mark>:  <mark>XGBoost</mark>  <mark>numpy</mark>  <mark>pandas</mark>  <mark>ts-fresh</mark>  <mark>pyod</mark>  <mark>ta</mark>  <mark>scikit-learn</mark>  <mark>matplotlib</mark>  <mark>pytest</mark>  <mark>tox</mark>
          
          <img src="images/db_logo.jpg" width="25" height="25" /> <mark>DB stack</mark>:  <mark>Oracle</mark>  <mark>PL/SQL</mark>  <mark>Hive</mark>

  - title:  #  Experience and Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BD Polska
        link: https://bdpolska.com/
        link_text: https://bdpolska.com/
        sub_title: Data Scientist / Data Engineer
        caption: June 2018 - June 2019
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          <mark>fuel quality prediction</mark>  <mark>Cox regression</mark>  <mark>data warehouse development</mark> 
          
          - data warehouse development - developing database structure and ETL jobs for largest polish petroleum firm logistics department; ETL processes started at *.csv or *.pdf files level 
          - fuel quality prediction - development of R-based regression model and deployment with MS SQLServer Machine Learning / R Services for live predictions
          - Cox model development for fuel filters survivability prediction  
          
            
             
          <img src="images/r_logo.png" width="25" height="25" />  <mark>R</mark>:  <mark>tidyr</mark>  <mark>glm</mark>
          
          <img src="images/python.jpg" width="25" height="25" /> <mark>Python3.7.9</mark>:  <mark>lifelines</mark>  <mark>pandas</mark>  <mark>matplotlib</mark>
          
          <img src="images/db_logo.jpg" width="25" height="25" /> <mark>DB stack</mark>:  <mark>T-SQL</mark>  <mark>MS ML/R-Services</mark>  <mark>MS SSIS</mark>  <mark>MS SQL Server 2016</mark>

  - title:  #  Experience and Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Samsung R&D Institute Poland
        link: https://samsungrd.pl/
        link_text: https://samsungrd.pl/
        sub_title: Junior ML Engineer / AI Engineer
        caption: June 2017 - June 2018
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          <mark>predictive autoscaling</mark>  <mark>predictive cloud maintenance</mark>  <mark>churn prediction</mark>  <mark>ML</mark> 
          
          - developing mobile assistant (Bixby) log-based analytical use cases (churn prediction, user activity prediction) on local and cloud infrastructure
          - development of predictive analytics for cloud infrastructure (disk usage prediction) using various approaches, e.g. Holt-Winters, ARIMA, Prophet
          - development of automatic autoscaling PoC for openstack compute following this [paper](https://ieeexplore.ieee.org/document/7892598); 
          PoC included automatic cluster spawning, applying load and autoscaling, models were trained using metrics from [wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page).
          
             
          <img src="images/r_logo.png" width="25" height="25" />  <mark>R</mark>:  <mark>ets</mark>  <mark>tidyr</mark>  <mark>ggplot</mark>
          
          <img src="images/python.jpg" width="25" height="25" /> <mark>Python3.7.9</mark>:  <mark>statsmodels</mark>  <mark>scikit-learn</mark>  <mark>pandas</mark>  <mark>matplotlib</mark>
          
          <img src="images/db_logo.jpg" width="25" height="25" /> <mark>Data stack</mark>:  <mark>Hive</mark>  <mark>Influx</mark>  <mark>Hortonworks Data Platform</mark>  <mark>OpenStack</mark>  <mark>Grafana</mark>


  - title:  #  Experience and Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MI^2 Data Lab
        link: https://www.mi2.ai/
        link_text: https://www.mi2.ai/
        sub_title: ML intern
        caption: February 2016 - June 2017
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          <mark>job offer classification</mark>  <mark>ML</mark>  <mark>web scraping</mark> 
          
          - working on a job classification project ["Is this an offer for a Data scientist"](http://smarterpoland.pl/index.php/2017/01/is-it-a-job-offer-for-a-data-scientist/)
          - helping with whyR 2017 conference organization
          
             
          <img src="images/r_logo.png" width="25" height="25" />  <mark>R</mark>:  <mark>XGBoost</mark>  <mark>randomForest</mark>  <mark>glm</mark>  <mark>tidyr</mark>  <mark>ggplot</mark>  <mark>web scraping</mark>
          
          <img src="images/db_logo.jpg" width="25" height="25" /> <mark>DB</mark>:  <mark>PostgreSQL</mark>


  - title:  #  Experience and Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Air force Institute of Technology
        link: https://itwl.pl/
        link_text: https://itwl.pl/
        sub_title: R&D Engineer
        caption: November 2015 - December 2019
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          UAV’s conceptual, structural and aerodynamic analysis and design


  - title: Courses # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: coursera / deeplearning.ai
        caption: May 2016 - until now
        sub_title: online ML / AI specializations
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - [Deep Learning Specialization](https://www.coursera.org/specializations/deep-learning) by deeplearning.ai
          - [TensorFlow Developer Specialization](https://www.coursera.org/professional-certificates/tensorflow-in-practice) by deeplearning.ai
          - [Tensorflow: Advanced Techniques Specialization](https://www.coursera.org/specializations/tensorflow-advanced-techniques) by deeplearning.ai
          - [Mathematics for Machine Learning and Data Science](https://www.coursera.org/specializations/mathematics-for-machine-learning-and-data-science#courses) by deeplearning.ai
          - [Reinforcement Learning Specialization](https://www.coursera.org/specializations/reinforcement-learning) by University of Alberta
          - [In-depth introduction to machine learning](https://www.dataschool.io/15-hours-of-expert-machine-learning-videos/)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Polish-Japanese Academy of Information Technology
        caption: March 2016 - February 2017
        sub_title: postgraduate degree
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Systems, applications and databases. Topics covered: OOP in JAVA, relational databases(basics of design and SQL programming).

  - title: # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Warsaw University of Technology
        caption: October 2009 - July 2015
        sub_title: B.Sc and M.Sc. degrees
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Finished studies at the Faculty of Power and Aeronautical Engineering, two specializations completed (“Aerospace Engineering” and “Aerospace Propulsion Systems”). 
          B.Sc final college grade: very good, M.Sc.final college grade: excellent (summacumlaude).
                    
  - title: Languages # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
#        title: Warsaw University of Technology
#        caption: October 2009 - July 2015
#        sub_title: B.Sc and M.Sc. degrees
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          - Polish - native
          - English - fluent in writing and speaking (FCE - B, IELTS 8/9 earned in 2018)
          - German - communicative


#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
